openapi: 3.0.3
info:
  title: Agent Service API
  version: 1.0.0
  description: API for agent services running on Azure Functions.

servers:
  - url: https://agents-workshop-dummy-api.azurewebsites.net/

paths:
  /api/agent:
    post:
      summary: Call an agent
      operationId: callAgent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                agent:
                  type: string
                  description: Agent ID (optional, defaults to env)
                message:
                  type: string
                  description: Message to send to the agent
                threadId:
                  type: string
                  description: Thread ID to use (required)
              required:
                - message
                - threadId
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /api/thread:
    post:
      summary: Create a new thread
      operationId: createThread
      responses:
        '200':
          description: Thread created
          content:
            application/json:
              schema:
                type: object
                properties:
                  threadId:
                    type: string

  /api/programmers/best:
    get:
      summary: Get the best programmer
      operationId: getBestProgrammer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  company:
                    type: string